from django.urls import path
from . import views
from .views import (
    TaskListView,
    ProjectListView,
    TeamListView,
    WorkerDetailView,
    WorkerProfileUpdateView,
    WorkerCreateView,
    WorkerListView,
    TeamDetailView,
    TeamDeleteView,
    TeamUpdateView,
    TeamCreateView,
    ProjectDetailView,
    ProjectUpdateView,
    WorkerDeleteView,
    ProjectCreateView,
    ProjectDeleteView,
    TaskTypeListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    PositionListView,
    PositionCreateView,
    PositionUpdateView,
    PositionDeleteView,
    UserTaskListView,
    TaskToggleView,
    LoggedWorkerDetailView,
    TaskDetailView,
)

app_name = "manager"
urlpatterns = [
    path("", views.index, name="index"),
    path("tasks/", TaskListView.as_view(), name="tasks-list"),
    path("user-tasks/", UserTaskListView.as_view(), name="user-tasks-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<int:pk>/toggle/", TaskToggleView.as_view(), name="task-toggle"),
    path("task-types/", TaskTypeListView.as_view(), name="task-types-list"),
    path("task-types/create", TaskTypeCreateView.as_view(), name="task-type-create"),
    path(
        "task-types/<int:pk>/update",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "task=types/<int:pk>/delete",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path("projects/", ProjectListView.as_view(), name="projects-list"),
    path("projects/create", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>", ProjectDetailView.as_view(), name="project-detail"),
    path(
        "projects/<int:pk>/update", ProjectUpdateView.as_view(), name="project-update"
    ),
    path(
        "projects/<int:pk>/delete", ProjectDeleteView.as_view(), name="project-delete"
    ),
    path("teams/", TeamListView.as_view(), name="teams-list"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update", TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete", TeamDeleteView.as_view(), name="team-delete"),
    path("workers/", WorkerListView.as_view(), name="workers-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/profile/", LoggedWorkerDetailView.as_view(), name="worker-profile"),
    path(
        "workers/<int:pk>/update",
        WorkerProfileUpdateView.as_view(),
        name="worker-update",
    ),
    path("workers/create", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/delete", WorkerDeleteView.as_view(), name="worker-delete"),
    path("tags/", TagListView.as_view(), name="tags-list"),
    path("tags/create", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete", TagDeleteView.as_view(), name="tag-delete"),
    path("positions/", PositionListView.as_view(), name="positions-list"),
    path("positions/create", PositionCreateView.as_view(), name="position-create"),
    path(
        "positions/<int:pk>/update",
        PositionUpdateView.as_view(),
        name="position-update",
    ),
    path(
        "positions/<int:pk>/delete",
        PositionDeleteView.as_view(),
        name="position-delete",
    ),
]
