# Generated by Django 6.0.1 on 2026-01-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0002_alter_worker_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tasks", to="manager.tag"),
        ),
    ]
