# Generated by Django 6.0.1 on 2026-01-17 18:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_task_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-priority"]},
        ),
    ]
