# Generated by Django 6.0.1 on 2026-01-22 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0004_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="name",
            field=models.CharField(
                max_length=250,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only alphanumeric characters and spaces are allowed.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(
                max_length=250,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only alphanumeric characters and spaces are allowed.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=250,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only alphanumeric characters and spaces are allowed.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                max_length=250,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only alphanumeric characters and spaces are allowed.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tasktype",
            name="name",
            field=models.CharField(
                max_length=250,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only alphanumeric characters and spaces are allowed.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(
                max_length=250,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only alphanumeric characters and spaces are allowed.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="first_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only alphanumeric characters and spaces are allowed.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="last_name",
            field=models.CharField(
                max_length=150,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Only alphanumeric characters and spaces are allowed.",
                        regex="^[a-zA-Z0-9_-]+$",
                    )
                ],
            ),
        ),
    ]
